# Generated by Django 3.2.25 on 2024-04-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostType', models.CharField(max_length=55)),
                ('content', models.CharField(max_length=55)),
            ],
        ),
    ]
